version: 2
jobs:
  buildAndDeploy:
    machine: true
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name : build-docker-image
          command: |
            docker build -t quay.io/wealthwizards/kube-housekeeper .
      - deploy:
          name : deploy-docker-image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker push quay.io/wealthwizards/kube-housekeeper
  buildDockerImage:
    machine: true
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name : build-docker-image
          command: |
            docker build -t quay.io/wealthwizards/kube-housekeeper  .
workflows:
  version: 2
  build_deploy:
    jobs:
      - buildDockerImage:
          filters:
            branches:
              ignore: master
      - buildAndDeploy:
          filters:
            branches:
              only: master